"""add composite org_created indexes

Revision ID: 4b99c522e89c
Revises: 458c55858e33
Create Date: 2026-08-31 02:12:28.532179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b99c522e89c'
down_revision: Union[str, Sequence[str], None] = '458c55858e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.create_index('ix_clients_org_created', 'clients', ['organization_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.create_index('ix_invoices_org_created', 'invoices', ['organization_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.create_index('ix_projects_org_created', 'projects', ['organization_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_prospects_organization_id'), table_name='prospects')
    op.create_index('ix_prospects_org_created', 'prospects', ['organization_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_quotes_organization_id'), table_name='quotes')
    op.create_index('ix_quotes_org_created', 'quotes', ['organization_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_org_created', table_name='quotes')
    op.create_index(op.f('ix_quotes_organization_id'), 'quotes', ['organization_id'], unique=False)
    op.drop_index('ix_prospects_org_created', table_name='prospects')
    op.create_index(op.f('ix_prospects_organization_id'), 'prospects', ['organization_id'], unique=False)
    op.drop_index('ix_projects_org_created', table_name='projects')
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.drop_index('ix_invoices_org_created', table_name='invoices')
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.drop_index('ix_clients_org_created', table_name='clients')
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    # ### end Alembic commands ###
